#!/bin/bash

# Environment Setup Script for AstroAI
echo "🔧 AstroAI Environment Setup"
echo "============================="

echo ""
echo "📝 Required Environment Variables for Backend:"
echo "---------------------------------------------"
echo "1. MONGODB_URI - Your MongoDB connection string"
echo "   Example: mongodb+srv://user:password@cluster.mongodb.net/astroai"
echo ""
echo "2. JWT_SECRET - A secure secret for JWT tokens"
echo "   Example: your-super-secret-jwt-key-change-this"
echo ""
echo "3. GEMINI_API_KEY - Your Google Gemini API key"
echo "   Get from: https://makersuite.google.com/app/apikey"
echo ""
echo "4. EMAIL_USER - Your email address for sending emails"
echo "   Example: your-email@gmail.com"
echo ""
echo "5. EMAIL_PASS - Your email app password (not regular password)"
echo "   For Gmail: Generate an app password from Google Account settings"
echo ""
echo "6. REDIS_URL - Your Redis connection string (optional)"
echo "   Example: redis://user:password@host:port"
echo ""

echo "🚀 Next Steps:"
echo "==============="
echo "1. Go to your Vercel project dashboard"
echo "2. Click on 'Settings' → 'Environment Variables'"
echo "3. Add all the above variables with their values"
echo "4. Redeploy your project"
echo ""

echo "🌐 Quick Setup Links:"
echo "====================="
echo "- MongoDB Atlas: https://www.mongodb.com/atlas"
echo "- Gemini API: https://makersuite.google.com/app/apikey"
echo "- Redis: https://redis.com/try-free"
echo ""

echo "⚠️  Important Notes:"
echo "===================="
echo "- Never commit your .env file to git"
echo "- Use strong, unique secrets"
echo "- Enable IP whitelisting for MongoDB"
echo "- Use app passwords for email (not regular passwords)"
echo ""

echo "✅ After setting up environment variables:"
echo "======================================="
echo "1. Run: vercel --prod (in api-backend directory)"
echo "2. Then: vercel --prod (in website directory)"
echo "3. Your app will be live! 🎉"
