import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { KundliReport } from '../api/reports';

export const generateKundliPDF = async (kundliReport: KundliReport): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }
  };

  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number = 12, fontStyle: string = 'normal') => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    const lineHeight = fontSize * 0.35;
    
    checkPageBreak(lines.length * lineHeight);
    
    lines.forEach((line: string) => {
      pdf.text(line, margin, yPosition);
      yPosition += lineHeight;
    });
    
    return lines.length * lineHeight;
  };

  // Title Page
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Kundli Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'normal');
  pdf.text(kundliReport.birth_details.full_name, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  pdf.setFontSize(12);
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  // Birth Details Section
  checkPageBreak(40);
  addText('Birth Details', 18, 'bold');
  yPosition += 5;
  
  const birthDetails = [
    `Name: ${kundliReport.birth_details.full_name}`,
    `Date of Birth: ${kundliReport.birth_details.date_of_birth}`,
    `Time of Birth: ${kundliReport.birth_details.time_of_birth}`,
    `Place of Birth: ${kundliReport.birth_details.place_of_birth}`
  ];

  birthDetails.forEach(detail => {
    addText(detail);
  });
  yPosition += 10;

  // Core Chart Information
  checkPageBreak(40);
  addText('Core Chart Information', 18, 'bold');
  yPosition += 5;
  
  const coreChart = [
    `Ascendant: ${kundliReport.chart_data.ascendant}`,
    `Moon Sign: ${kundliReport.chart_data.moon_sign}`,
    `Sun Sign: ${kundliReport.chart_data.sun_sign}`,
    `Nakshatra: ${kundliReport.chart_data.nakshatra}`
  ];

  coreChart.forEach(info => {
    addText(info);
  });
  yPosition += 10;

  // Planetary Positions
  checkPageBreak(60);
  addText('Planetary Positions', 18, 'bold');
  yPosition += 5;
  
  Object.entries(kundliReport.chart_data.planets).forEach(([planet, data]) => {
    const planetInfo = `${planet.charAt(0).toUpperCase() + planet.slice(1)}: ${data.sign} (${data.degree}°)`;
    addText(planetInfo);
  });
  yPosition += 10;

  // Houses Information
  checkPageBreak(60);
  addText('12 Houses', 18, 'bold');
  yPosition += 5;
  
  Object.entries(kundliReport.chart_data.houses).forEach(([house, sign]) => {
    const houseInfo = `House ${house}: ${sign}`;
    addText(houseInfo);
  });
  yPosition += 15;

  // AI Interpretation Sections
  const interpretations = [
    { title: 'Personality', content: kundliReport.interpretation.personality },
    { title: 'Strengths', content: kundliReport.interpretation.strengths },
    { title: 'Challenges', content: kundliReport.interpretation.challenges },
    { title: 'Career', content: kundliReport.interpretation.career },
    { title: 'Relationships', content: kundliReport.interpretation.relationships },
    { title: 'Health', content: kundliReport.interpretation.health },
    { title: 'Spiritual Path', content: kundliReport.interpretation.spiritual_path }
  ];

  interpretations.forEach(interpretation => {
    if (interpretation.content) {
      checkPageBreak(40);
      addText(interpretation.title, 16, 'bold');
      yPosition += 3;
      addText(interpretation.content);
      yPosition += 10;
    }
  });

  // Important Yogas
  if (kundliReport.interpretation.important_yogas && kundliReport.interpretation.important_yogas.length > 0) {
    checkPageBreak(40);
    addText('Important Yogas', 16, 'bold');
    yPosition += 5;
    
    kundliReport.interpretation.important_yogas.forEach((yoga, index) => {
      addText(`${index + 1}. ${yoga}`);
    });
  }

  // Footer on each page
  const totalPages = pdf.internal.pages.length - 1; // pages array includes a dummy page at index 0
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    pdf.text('Generated by AstroAI - Vedic Astrology Platform', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  // Save the PDF
  const fileName = `Kundli_${kundliReport.birth_details.full_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};

export const generateKundliPDFFromElement = async (elementId: string, fileName: string): Promise<void> => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff'
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(fileName);
  } catch (error) {
    console.error('Error generating PDF from element:', error);
    throw new Error('Failed to generate PDF from the provided element');
  }
};
